# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: services/waitlist.service.proto for package 'RPC'

require 'grpc'
require 'services/waitlist.service_pb'

module RPC
  module WaitlistService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'RPC.WaitlistService'

      rpc :create, ::WaitlistCreate, ::Waitlist
      rpc :get, ::Waitlist, ::Waitlist
      rpc :update, ::Waitlist, ::Waitlist
      rpc :delete, ::Waitlist, ::Deleted
    end

    Stub = Service.rpc_stub_class
  end
end
