# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: services/obsession.service.proto for package 'RPC'

require 'grpc'
require 'services/obsession.service_pb'

module RPC
  module ObsessionService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'RPC.ObsessionService'

      rpc :create, ::RPC::ObsessionCreate, ::RPC::Obsession
      rpc :get, ::RPC::Obsession, ::RPC::Obsession
      rpc :update, ::RPC::Obsession, ::RPC::Obsession
      rpc :delete, ::RPC::Obsession, ::RPC::Deleted
    end

    Stub = Service.rpc_stub_class
  end
end
