# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/waitlist.service.proto

require 'google/protobuf'

require 'definitions/waitlist_pb'
require 'definitions/generics_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("services/waitlist.service.proto", :syntax => :proto3) do
  end
end

module RPC
end
