# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: definitions/generics.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("definitions/generics.proto", :syntax => :proto3) do
    add_message "RPC.Deleted" do
      optional :deleted, :bool, 1
    end
  end
end

module RPC
  Deleted = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RPC.Deleted").msgclass
end
