# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: definitions/product.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("definitions/product.proto", :syntax => :proto3) do
    add_message "RPC.Product" do
      optional :id, :int32, 1
    end
  end
end

module RPC
  Product = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RPC.Product").msgclass
end
