# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: definitions/user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("definitions/user.proto", :syntax => :proto3) do
    add_message "RPC.User" do
      optional :id, :int32, 1
    end
  end
end

module RPC
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RPC.User").msgclass
end
